import testCompleteness from "./completeness";
import { BLACKOUT_END, BLACKOUT_START, BOSS_ENEMY_DEFEATED, FAILURE_BASE_DESTROYED, FOUND_ALL_LOST_MINERS, FOUND_HOARD, FOUND_HQ, FOUND_LM_BREADCRUMB, FOUND_LOST_MINERS, FOUND_SLUG_NEST, GAS_LEAK_NO_AIR, MOB_FARM_NO_LONGER_BLOCKING } from "./events";

testCompleteness(
  FOUND_ALL_LOST_MINERS,
  FOUND_HOARD,
  FOUND_HQ,
  FOUND_LM_BREADCRUMB,
  FOUND_LOST_MINERS,
  FOUND_SLUG_NEST,
  FAILURE_BASE_DESTROYED,
  BOSS_ENEMY_DEFEATED,
  BLACKOUT_START,
  BLACKOUT_END,
  MOB_FARM_NO_LONGER_BLOCKING,
  GAS_LEAK_NO_AIR,
)