import {
  BUILD_POWER_GC_FIRST,
  BUILD_POWER_GC_LAST,
  BUILD_POWER_GC_PENULTIMATE,
  BUILD_POWER_SS_FIRST,
  BUILD_POWER_SS_LAST,
  BUILD_POWER_SS_PENULTIMATE,
} from "./build_and_power";
import { FAILURE, SUCCESS } from "./conclusions";
import {
  BLACKOUT_END,
  BLACKOUT_START,
  BOSS_ENEMY_DEFEATED,
  FAILURE_BASE_DESTROYED,
  FOUND_ALL_LOST_MINERS,
  FOUND_HOARD,
  FOUND_HQ,
  FOUND_LM_BREADCRUMB,
  FOUND_LOST_MINERS,
  FOUND_SLUG_NEST,
  GAS_LEAK_INSUFF_AIR,
  GAS_LEAK_NO_AIR,
  MOB_FARM_NO_LONGER_BLOCKING,
  NOMADS_SETTLED,
} from "./events";
import { NAME } from "./names";
import ORDERS from "./orders";
import {
  DID_SPAWN_HOARD,
  DID_SPAWN_ROGUE,
  DID_SPAWN_SEAM,
  WARN_APPROACHING_HOARD,
} from "./pandora";
import PREMISE from "./premise";
import { SEISMIC_FORESHADOW, SEISMIC_FORESHADOW_AGAIN } from "./seismic";

const ALL_GRAPHS = [
  BLACKOUT_END,
  BLACKOUT_START,
  BOSS_ENEMY_DEFEATED,
  BUILD_POWER_GC_FIRST,
  BUILD_POWER_GC_LAST,
  BUILD_POWER_GC_PENULTIMATE,
  BUILD_POWER_SS_FIRST,
  BUILD_POWER_SS_LAST,
  BUILD_POWER_SS_PENULTIMATE,
  DID_SPAWN_HOARD,
  DID_SPAWN_ROGUE,
  DID_SPAWN_SEAM,
  FAILURE_BASE_DESTROYED,
  FAILURE,
  FOUND_ALL_LOST_MINERS,
  FOUND_HOARD,
  FOUND_HQ,
  FOUND_LM_BREADCRUMB,
  FOUND_LOST_MINERS,
  FOUND_SLUG_NEST,
  GAS_LEAK_INSUFF_AIR,
  GAS_LEAK_NO_AIR,
  MOB_FARM_NO_LONGER_BLOCKING,
  NAME,
  NOMADS_SETTLED,
  ORDERS,
  PREMISE,
  SEISMIC_FORESHADOW,
  SEISMIC_FORESHADOW_AGAIN,
  SUCCESS,
  WARN_APPROACHING_HOARD,
] as const;
export default ALL_GRAPHS;
